### ISSUE TITLE
Issues with big integers

### ISSUE THREAD

**Issue by prakashgp** [kylefarris/node-querybuilder#10]
It converts string values like `23842563958810573` into `23842563958810572` which took half day to find out !

**Comment by kylefarris** [comment]
Hmm... I'm not sure if this is an issue with the mysql driver or if it's with the querybuilder. Any ideas?

**Comment by prakashgp** [comment]
I think it is a problem with JavaScript that it can't handle such big
numbers.(such as Facebook campaign ids)

I can avoid this by converting number to string before passing to query
builder.

But still,  the problem with querybuilder is it detects the numerical
string and converts it into number (my guess)
This happens when a number is passed to functions like `where() `
but it works when numerical string is used in raw queries

**Comment by kylefarris** [comment]
Ah, interesting. Thanks for the feedback--I'll take a look at what I'm doing and see if there are some bad assumptions, and, hence, conversions being made.
