### ISSUE TITLE
Use of Object.assign

### ISSUE THREAD

**Issue by louisl** [kylefarris/node-querybuilder#11]
FYI I couldn't use this in my Strongloop (express js) project without adding a shim for Object.assign in the mysql/adapters.js

The error wasn't very helpful either.

```
{"error":{"name":"Error","status":500,"message":"Couldn't load the Connection library for mysql({}): TypeError: undefined is not a function","stack":"Error: Couldn't load the Connection library for mysql({}): TypeError: undefined is not a function\n    at get_adapter (/Users/xxx/Sites/xxx/node_modules/node-querybuilder/index.js:124:10)\n ...
```
I needed to add `var assign = Object.assign || require('object.assign');` and change instances of `Object.assign` to `assign` in mysql/adapters.js.

**Comment by kylefarris** [comment]
Must be running an older version of Node.js that doesn't support this feature yet. I can update the docs to reflect the minimum Node version if that helps. Any ideas? I don't really want to add the shim into the code since its been supported since at least Node v4.0.0 (we're currently on v8.x).

**Comment by louisl** [comment]
Ooh it was a while back now and I've updated all sort of things since then, not sure if it's still a problem. I'll take a look next time I'm on that job, meanwhile I'll close this and the reference is here if anyone else needs it.

Thanks

**Comment by kylefarris** [comment]
Thanks for your response @louisl.
