### ISSUE TITLE
throw new Error("No database driver specified!");

### ISSUE THREAD

**Issue by afzydev** [kylefarris/node-querybuilder#13]
Hi
Thanks for the awesome repo.

Please check my code below and tell me what is the problem going on.

```
db.json file code :
{
    "host": "localhost",
    "user": "root",
    "password": "root",
    "database": "larastrip",
    "pool_size": 100
}
```
This is the way i am importing below:
```
import Connection from '../lib/database/db.json';
const qb = require('node-querybuilder').QueryBuilder(Connection);
```
This is the error which i am getting:

> throw new Error("No database driver specified!");

**Comment by kylefarris** [comment]
@afzydev Try this...

```javascript
const qb = require('node-querybuilder').QueryBuilder(Connection, 'mysql');
```

'mysql' should be the default for the second parameter, but, it doesn't hurt to provide it. I'll see what's going on in the code that might be preventing this from working, but, this should get you going in the meantime.

Kyle

**Comment by kylefarris** [comment]
I see the bug. I'm going to fix it in a patch I'm about to release. Sorry for the trouble.

**Comment by kylefarris** [comment]
The bug has been fixed and a patch has been released. Please update to version 1.0.2 if you don't want to provide the second and third parameters.

**Comment by kylefarris** [comment]
There was a bug in that patch. Please go to 1.0.3. Sorry.

**Comment by afzydev** [comment]
@kylefarris 

Thanks for your awesomeness :+1: 

There is one more problem when I am calling where function it is giving me an error : 

```
DB.select('*')
		.where('report_id',1)
		.get('t_report_detail', (err,response) => {
		    if (err) return console.error("Uh oh! Couldn't get results: " + err.msg);
		        // SELECT `name`, `position` FROM `planets` WHERE `type` = 'rocky' AND `diameter` < 12000
		        console.log("Query Ran: " + DB.last_query());
		        // [{name: 'Mercury', position: 1}, {name: 'Mars', position: 4}]
		        res.json({
			      results: response,
			    });
			}
		);	
```

`{"message":"Cannot find module '../../node_modules/mysql/lib/protocol/SqlString.js'","stack":"Error: Cannot find module '../../node_modules/mysql/lib/protocol/SqlString.js'\n at Function.Module._resolveFilename (module.js:440:15)\n at Function.Module._load (module.js:388:25)\n at Module.require (module.js:468:17)\n at require (internal/module.js:20:19)\n at qb_escape (/var/www/html/visualization-framework/server/node_modules/node-querybuilder/drivers/mysql/query_builder.js:281:27)`


Thanks
