### ISSUE TITLE
Unable to 'promisify' QueryBuilder

### ISSUE THREAD

**Issue by masterjaso** [kylefarris/node-querybuilder#17]
I've tried using util.promisify as well as just manually building the function below and it seems that promises won't apply properly

`function queryBuilder(options, driver, type){
  return new Promise(function(fulfill, reject){
    qb.QueryBuilder(options, driver, type, function(err, res){
      if(err) reject(err);
      else fulfill(res);
    });
  });
}.`

Is there something I'm missing, or is there a way that this could be promisified to work with async/await?

My overarching use case is that I have multiple configurations for X different Databases.  I want to create a QueryBuilder pool for each of them so that my service can interact with them all.  However, pass configs to QueryBuilder in a for loop or Promise.all->map it only sets up multiple pools for one of the entries.

Thanks for any time and help you can provide.

**Comment by kylefarris** [comment]
@masterjaso I think this is actually related to the multiple-pool enhancement request #18. Am I correct? Or is it simply that you cannot promisify in any way?

**Comment by kylefarris** [comment]
Feature officially added as of v2.1.0.
