### ISSUE TITLE
can we create table with query builder?

### ISSUE THREAD

**Issue by rahulsharma841990** [kylefarris/node-querybuilder#19]
Hello, I am working on some framework and wan to create tables dynamically  and i just want to know that is it possible to create table using this query builder?

**Comment by dustinmolieri** [comment]
Directly from the Documentation, which can be found here:
https://www.npmjs.com/package/node-querybuilder

"There are scenarios when using this method may be required; for instance, if you need to run a very specific type of command on your database that is not typical of a standard, CRUD-type query (ex. user permissions or creating a view)."

![query](https://user-images.githubusercontent.com/28568900/35129032-6cd027e2-fc6e-11e7-90df-d2fe48b1a9f5.jpg)

**Comment by kylefarris** [comment]
@rahulsharma841990 As @dustinmolieri has pointed out, you absolutely can do it by just using the `query` method. If you'd like to write a new driver file to allow for creating/delete/truncating tables and databases, please feel free to do so and submit a PR. I would probably call this file `/drivers/mysql/db_forge.js`.
