### ISSUE TITLE
Add installation documentation for module `underscore`

### ISSUE THREAD

**Issue by baaskoen** [kylefarris/node-querybuilder#2]
If I'm following the installation documentation and try to configure Node Query Builder, I'm getting the following error:

> Error: Couldn't load the Connection library for mysql({"user":"root","host":"localhost","database":"myDatabase","password":"myPassword","pool_size":50}): Error: Cannot find module 'underscore'

Perhaps it is a good idea to add  `npm install underscore` to the documentation?

Great work though :+1:

**Comment by malles** [comment]
IT should be added to the dependancies.
The tests on travis also fail because of missing underscore

**Comment by kylefarris** [comment]
I was only using underscore for its `extend` method. Node has had the native es2015 `Object.assign` method for some time now so I've removed the underscore dependency and changed all instances of `_.extend` to `Object.assign`. That does mean, however, that Node version >= 4.0 is now required (was 0.10). I don't think this is too much of a stretch, though, seeing as version 7+ is out now.

Travis builds are now passing.
