### ISSUE TITLE
[mysql] like does not escape apostrophe

### ISSUE THREAD

**Issue by Flamenco** [kylefarris/node-querybuilder#30]
The apostrophe is not escaped in this case:
```js
let titleQuery = "it's"
qb.like('s.title', titleQuery, 'both')
```

The produced SQL has invalid syntax
```sql
AND `s`.`title` LIKE '%it's%'
```

The documentation states:
> All fields are escaped automatically, no exceptions.

**Comment by kylefarris** [comment]
Yikes, I'll right a test and get it fixed for v2. Thanks for the bug report.

**Comment by kylefarris** [comment]
This is officially fixed in the v2 branch. Beta should be out soon.
