### ISSUE TITLE
Return promises from get()

### ISSUE THREAD

**Issue by Flamenco** [kylefarris/node-querybuilder#31]
I wrapped promises around the return of get() and it works quite well.  Not only does it clean up my code, but I can also add a single _finally_ to release the connection after a chain of queries.

Here's an example.

```js
          .like('s.title', x(titleQuery), 'both')
          .limit(20)
          .get_p()
          .then(res => {
            response.send(res)
          })
          .catch(reason=>response.status(500).send(reason))
          .then(value => qb.release())
```

Could this, or just simply returning a promise from get() if a callback is not provided, be added to the official API?

**Comment by kylefarris** [comment]
We could potentially "promisify" the library as an option for users. This would probably be a v3 enhancement.

**Comment by kylefarris** [comment]
Promise features officially added as of v2.1.0.
