### ISSUE TITLE
Allow where_in and where_not_in to have empty arrays

### ISSUE THREAD

**Issue by Flamenco** [kylefarris/node-querybuilder#34]
I have to put many checks in my code for filters because where_in('foo',[]) will throw an error.
Please consider allowing these conditions.

**Comment by Flamenco** [comment]
<img width="516" alt="screen shot 2018-07-19 at 2 43 19 pm" src="https://user-images.githubusercontent.com/819940/43008435-1b223f2c-8c09-11e8-9b3b-99639817c3e2.png">

**Comment by kylefarris** [comment]
Would you rather is just silently ignore it/

**Comment by Flamenco** [comment]
Yes.  Ignore will be great.  No need to encode in SQL.

**Comment by kylefarris** [comment]
This is officially fixed in the v2 branch. Beta should be out soon.

**Comment by kylefarris** [comment]
@Flamenco Thank you for being so active in reporting issues. A v2 Beta is officially out on NPM. If you wouldn't mind testing it, that would be very much appreciated.

You can install the beta like so:

```
npm i node-querybuilder@next
```

If you need to submit issues for it, please prefix the issue with **v2Beta:**

Thanks again!

**Comment by Flamenco** [comment]
@kylefarris I am not sure how you implemented this, but maybe instead of ignoring, replace where_in('foo', []) with false or (1=0) and where_not_in('foo', []) with true or (1=1).  I am about to switch over to v2 and I have some complex queries that may have issues.
