### ISSUE TITLE
get(...) should have an optional where parameter

### ISSUE THREAD

**Issue by Flamenco** [kylefarris/node-querybuilder#50]
It would make sense for the `get` method to allow a `where` parameter.  This would match the API of the other methods as well, such as `insert` and `delete`.

```
qb.get('gizmos', {color:'red'}, (err, rows) => { 
})
```
or
```
await qb.get('gizmos', {color:'red'})
```

**Comment by kylefarris** [comment]
You can use the `get_where` method to accomplish this.
