### ISSUE TITLE
doesn't escape value passed to like()

### ISSUE THREAD

**Issue by prakashgp** [kylefarris/node-querybuilder#8]
It directly executes statements without escaping values passed to `like` function

**Comment by kylefarris** [comment]
I'll take a look.

**Comment by kylefarris** [comment]
@prakashgp Could you provide a sample query where this would happen? The tests I've written seem to indicate that they fields and values will be escaped unless I'm missing something. Thanks!

**Comment by prakashgp** [comment]
I'm currently using this code which escapes the value:
```

dbi.like(args.field, args.value.replace(/[\x00\n\r\\\'\"\x1a]/g, match => '\\' + match ) );
dbi.get('table_name');
console.log(campaign.dbi.last_query());

```
When i was using following code, it was not escaping values (observed from console.log as well as query error). I've also tried sql injection which worked perfect :)

```
dbi.like(args.field, args.value);
dbi.get('table_name');
console.log(campaign.dbi.last_query());
```

**Comment by kylefarris** [comment]
@prakashgp I'm very busy with my current workload (job). If you can put a PR in for this, I would forever grateful.

Thanks!

Kyle

**Comment by agravatfemina** [comment]
@kylefarris  I want to user like() for search/apply filters on query but I can not use MYSQL function with like() as it is not escaping the ` sign and also it is adding   AS in a query..   

Here is my sample line of code 
   **queryBuilder.like("LOWER(u.vName)",params.filters.name);**

Where as it resulting the OUTPUT in a query  like :

**AND  LOWER(u.vName) AS `LIKE '%femina%'`** 

Help me on this !
Thank you  in advance!

**Comment by louisl** [comment]
I'm not sure for @prakashgp but my problem was the same as @agravatfemina 

Seems to me it's this in query_builder.js:
```
// This is basically a bug fix for queries that use MAX, MIN, subqueries, etc.
// If a parenthesis is found we know that we do not need to
// escape the data or add a prefix.
if (item.indexOf('(') !== -1 || item.indexOf("'") !== -1) {
    const has_alias = item.lastIndexOf(')');
    let alias;
    if (has_alias >= 0) {
        alias = item.substr(has_alias + 1).replace(/\sAS\s/i,'').trim();
        alias = escape_identifiers(alias);
        if (alias != '')
            alias = ' AS ' + alias;
        item = item.substr(0,has_alias + 1);
    } else {
        alias = '';
    }

    return item + alias;
}
```
It appears to me that bit of code is assuming that if there is an opening bracket or single quote we need an 'AS' so it looks for one and removes it (without checking it exists), then protects the identifiers and puts it back on the end regardless of whether it existed or not.

Changing to this works for me:
```
// This is basically a bug fix for queries that use MAX, MIN, subqueries, etc.
// If a parenthesis is found we know that we do not need to
// escape the data or add a prefix.
if (item.indexOf('(') !== -1 || item.indexOf("'") !== -1) {
    const has_alias = item.indexOf('AS') !== -1 ? true : false;
    if (!has_alias) {
        return item;
    }
    const last_closing_bracket = item.lastIndexOf(')');
    let alias;
    if (last_closing_bracket >= 0) {
        alias = item.substr(last_closing_bracket + 1).replace(/\sAS\s/i,'').trim();
        alias = escape_identifiers(alias);
        if (alias != '') {
            alias = ' AS ' + alias;
        }
        item = item.substr(0, last_closing_bracket + 1);
    } else {
        alias = '';
    }

    return item + alias;
}
```
That will work with a back ticked query or without. eg.
```
query.or_like('CONCAT(`quote_prefix`.`prefix`, `quote`.`id`)', filter.where.search, 'both')

query.or_like('CONCAT(quote_prefix.prefix, quote.id)', filter.where.search, 'both')
```

Adding back ticks for the fields in functions is a job for another day/person!

**Comment by kylefarris** [comment]
This is officially fixed in the v2 branch. Beta should be out soon.
